enum class TokenType
{
    IDENTIFIER,
    KEYWORD,
    LITERAL,
    PUNCTUATOR,
    OPERATOR
};

// not required, identifiers are user inputted
enum class IndentiferToken
{
    VARIABLE,
    FUNCTION,
    MODULE,
    TYPE_INT,
    TYPE_FLOAT,
    TYPE_DOUBLE,
    TYPE_BOOL,
    TYPE_CHAR,
    TYPE_LONG,
    TYPE_SHORT,
    TYPE_VOID,
    TYPE_ANY,
    TYPE_POINTER,
    TYPE_UINT,
    TYPE_ULONH,
    TYPE_USHORT,
    TYPE_UCHAR
};

// PURPOSE_identifier
enum class KeywordToken
{
    VARIABLE_DECLARATION_LET,
    VARIABLE_DECLARATION_OPLET,    // optional let
    FUNCTION_DECLARATION_F,        // f
    FUNCTION_DECLARATION_F_VOID,   // f_
    FUNCTION_DECLARATION_F_PURE,   // f!
    FUNCTION_DECLARATION_F_LAMBDA, // f/
    FUNCTION_RETURN,
    CONDITIONAL_IF,
    CONDITIONAL_ELSE_IF,
    CONDITIONAL_ELSE,
    PATTERN_MATCH
};
// not required, strings are user inputted
enum class LiteralToken
{
    NUMERIC,
    STRING,
    BOOLEAN,
    NULL
};
enum class PunctuatorToken
{
    SEMICOLON,
    COLON,
    EXCLAMATION,
    QUOTE,
    DOUBLE_QUOTE,
    BRACKET,
    BRACE,
    PARENTHESES
};
enum class OperatorToken
{
    ARITHMETHIC_ADD,
    ARITHMETHIC_SUB,
    ARITHMETHIC_MUL,
    ARITHMETHIC_DIV,
    ARITHMETHIC_MOD,
    COMPARISON_EQ,
    COMPARISON_NEQ,
    COMPARISON_LT,
    COMPARISON_GT,
    COMPARISON_LTE,
    COMPARISON_GTE,
    LOGICAL_AND,
    LOGICAL_OR,
    LOGICAL_NOT,
    ASSIGNMENT_EQUALS,
    ASSIGNMENT_INCREMENT,
    ASSIGNMENT_DECREMENT,
    ASSIGNMENT_MUL,
    ASSIGNMENT_DIV,
    ASSIGNMENT_MOD,
    BITWISE_AND,
    BITWISE_OR,
    BITWISE_XOR,
    BITWISE_NEG,
    BITWISE_SL,
    BITWISE_SR,
    ARROW,
    INCREMENT,
    DECREMENT
};